### ISSUE TITLE
Set up instructions aren't complete

### ISSUE THREAD

**Issue by allenpark** [simhunt/wow#4]
There's things that presumably people who know Meteor would know but complete scrubs like me don't like how to set up a settings file or how to integrate with Drive/Discord/Twitter/etc. It'd be nice to know how to do those things

**Comment by jenna-h** [comment]
I'll update the README with some important stuff for Drive and Discord, and also how to deploy to wafflehaus.mit.edu. I don't personally use Twitter and I'm not sure that's useful for our team, so I'm going to leave that aside for now.
